name: publish
on: [workflow_dispatch]
jobs:
  build-artifacts:
    runs-on: macOS-13
    steps:
      - run: echo "TMPDIR=${TMPDIR}" >> $GITHUB_ENV
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - run: gem install kramdown-rfc2629
      - run: pip install xml2rfc
      - run: brew install enscript
      - uses: actions/checkout@v2.3.4 
      - run: kramdown-rfc2629 draft-ietf-ippm-responsiveness.md > ${{ env.TMPDIR }}/draft-ietf-ippm-responsiveness.xml
      - run: xml2rfc ${{ env.TMPDIR }}/draft-ietf-ippm-responsiveness.xml > ${{ env.TMPDIR }}/draft-ietf-ippm-responsiveness.txt
      - run: xml2rfc --html ${{ env.TMPDIR }}/draft-ietf-ippm-responsiveness.xml > ${{ env.TMPDIR }}/draft-ietf-ippm-responsiveness.html
      - run: enscript -B -o ${{ env.TMPDIR }}/draft-ietf-ippm-responsiveness.ps ${{ env.TMPDIR }}/draft-ietf-ippm-responsiveness.txt
      - run: pstopdf ${{ env.TMPDIR }}/draft-ietf-ippm-responsiveness.ps
      - uses: actions/upload-artifact@v3
        with:
          name: Publication
          path: ${{ env.TMPDIR }}/draft-ietf-ippm-responsiveness.xml
      - uses: actions/upload-artifact@v3
        with:
          name: Publication
          path: ${{ env.TMPDIR }}/draft-ietf-ippm-responsiveness.txt
      - uses: actions/upload-artifact@v3
        with:
          name: Publication
          path: ${{ env.TMPDIR }}/draft-ietf-ippm-responsiveness.pdf
      - uses: actions/upload-artifact@v3
        with:
          name: Publication
          path: ${{ env.TMPDIR }}/draft-ietf-ippm-responsiveness.html